apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: controller-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: grpc-agent
      protocol: GRPC
    hosts:
    - controller-agent.albertsons.opsmx.com
    tls:
      mode: PASSTHROUGH
