apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: azure-storage 
spec:
  hosts:
  - "albertsonstestsrini.blob.core.windows.net"
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS

