apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: googleapis 
spec:
  hosts:
  - "*.googleapis.com"
  - "*.docker.io"
  - "github.com"
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: NONE

