apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: oes-gate-route
spec:
  hosts:
  - "oesgate.albertsons.opsmx.com"
  gateways:
  - spinnaker-gateway
  http:
  - name: "gate-route"
    match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: oes-gate
        port:
          number: 8084