apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    version: v3
  name: nginx-v3
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      version: v3
  template:
    metadata:
      labels:
        app: nginx
        version: v3
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-volume
        configMap:
          name: nginx-v3
